DROP DATABASE IF EXISTS PROJECTSAPP;
CREATE DATABASE MYPROJECTSAPP;

USE MYPROJECTSAPP;

CREATE TABLE USERNAMES (
  USERNAME VARCHAR(40) PRIMARY KEY, 
  NAME VARCHAR(40),
  SURNAME VARCHAR(40),
  PASSWORD VARCHAR(255),
  IMAGE VARCHAR(100),
  FUNCTION VARCHAR(10),
  STATEMENT VARCHAR(10)
);

CREATE TABLE PROJECTS (
  USERNAME VARCHAR(40) NOT NULL,
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(80),
  DESCRIPTION VARCHAR(200),
  DELIVDATE VARCHAR(15),
  STATUS VARCHAR(15),
  PERCENT INT
);

CREATE TABLE TASKS (
  USERNAME VARCHAR(40) NOT NULL,
  IDPROJECT INT NOT NULL,
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(80),
  DESCRIPTION VARCHAR(200),
  STATUS VARCHAR(15)
);

CREATE TABLE FILES (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(40) NOT NULL,
  IDPROJECT INT NOT NULL,
  IDTASK INT NOT NULL,
  FILE VARCHAR(200)
);
